### ISSUE TITLE
0.2 documentation todo

### ISSUE THREAD

**Issue by irskep** [irskep/clubsandwich#11]
- [ ] `ScrollingTextView`
- [ ] `KeyAssignedListView`

**Comment by ItsMeThom-zz** [comment]
I added the missing docstrings for both classes and opened [this PR](https://github.com/irskep/clubsandwich/pull/15) for them. As mentioned in the PR I've no experience with sphinx so Im not sure if the .rst files need to be updates alongside these or if it will detect those changes automatically when you rebuild the documentation.

**Comment by irskep** [comment]
Thanks!!

**Comment by Zireael07** [comment]
You seem to have ditched asyncio in 7e4cb2638dea7adc4a148d842b11db6588d90607, but both the README and the documentation still mention relying on it?

Also, with asyncio gone, is there any reason for requiring Python 3?

**Comment by irskep** [comment]
I will not be backporting this to Python 2, which will be EOL'd this year. https://pythonclock.org

You're right that asyncio is a documentation bug. :-)
