### ISSUE TITLE
Point class does not work well with pickle in python3

### ISSUE THREAD

**Issue by eldarbogdanov** [irskep/clubsandwich#17]
Pickling Point instances, and unpickling them in a different python session, leads to a malfunctioning Point class on Python>=3.3. More specifically, its _hash member value is different from what a new identical Point would generate in this session. A way to reproduce it would be to pickle a dictionary with Points as keys, save result to a file, and then unpickle this file in a different python session and try to access the keys - dictionary would almost certainly return nothing.

The underlying issue is that starting with Python 3.3, the built-in hash() function returns results that are randomized across different python sessions: https://github.com/irskep/clubsandwich/blob/master/clubsandwich/geom.py#L33

**Comment by irskep** [comment]
Pickle is not widely used and I'm not interested in special cases to support it. Hashing is for dictionaries. :-)
